export const SHINDO = {
  SHINDO_4: "震度４",
  SHINDO_5_WEAK: "震度５弱",
  SHINDO_5_STRONG: "震度５強",
  SHINDO_6_WEAK: "震度６弱",
  SHINDO_6_STRONG: "震度６強",
  SHINDO_7: "震度７",
};

export const earthquakeData = [
  {
    period: "1910年代",
    intensities: {
      [SHINDO.SHINDO_4]: 3,
      [SHINDO.SHINDO_5_WEAK]: 0,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 0,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 3,
  },
  {
    period: "1920年代",
    intensities: {
      [SHINDO.SHINDO_4]: 85,
      [SHINDO.SHINDO_5_WEAK]: 54,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 4,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 143,
  },
  {
    period: "1930年代",
    intensities: {
      [SHINDO.SHINDO_4]: 91,
      [SHINDO.SHINDO_5_WEAK]: 40,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 2,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 133,
  },
  {
    period: "1940年代",
    intensities: {
      [SHINDO.SHINDO_4]: 97,
      [SHINDO.SHINDO_5_WEAK]: 11,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 4,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 112,
  },
  {
    period: "1950年代",
    intensities: {
      [SHINDO.SHINDO_4]: 65,
      [SHINDO.SHINDO_5_WEAK]: 4,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 0,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 69,
  },
  {
    period: "1960年代",
    intensities: {
      [SHINDO.SHINDO_4]: 251,
      [SHINDO.SHINDO_5_WEAK]: 37,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 0,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 288,
  },
  {
    period: "1970年代",
    intensities: {
      [SHINDO.SHINDO_4]: 123,
      [SHINDO.SHINDO_5_WEAK]: 15,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 1,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 139,
  },
  {
    period: "1980年代",
    intensities: {
      [SHINDO.SHINDO_4]: 168,
      [SHINDO.SHINDO_5_WEAK]: 19,
      [SHINDO.SHINDO_5_STRONG]: 0,
      [SHINDO.SHINDO_6_WEAK]: 1,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 188,
  },
  {
    period: "1990年代",
    intensities: {
      [SHINDO.SHINDO_4]: 289,
      [SHINDO.SHINDO_5_WEAK]: 35,
      [SHINDO.SHINDO_5_STRONG]: 4,
      [SHINDO.SHINDO_6_WEAK]: 5,
      [SHINDO.SHINDO_6_STRONG]: 0,
      [SHINDO.SHINDO_7]: 1,
    },
    total: 334,
  },
  {
    period: "2000年代",
    intensities: {
      [SHINDO.SHINDO_4]: 685,
      [SHINDO.SHINDO_5_WEAK]: 73,
      [SHINDO.SHINDO_5_STRONG]: 29,
      [SHINDO.SHINDO_6_WEAK]: 19,
      [SHINDO.SHINDO_6_STRONG]: 7,
      [SHINDO.SHINDO_7]: 1,
    },
    total: 814,
  },
  {
    period: "2010年代",
    intensities: {
      [SHINDO.SHINDO_4]: 771,
      [SHINDO.SHINDO_5_WEAK]: 114,
      [SHINDO.SHINDO_5_STRONG]: 44,
      [SHINDO.SHINDO_6_WEAK]: 15,
      [SHINDO.SHINDO_6_STRONG]: 7,
      [SHINDO.SHINDO_7]: 4,
    },
    total: 955,
  },
  {
    period: "2020年代",
    intensities: {
      [SHINDO.SHINDO_4]: 138,
      [SHINDO.SHINDO_5_WEAK]: 22,
      [SHINDO.SHINDO_5_STRONG]: 14,
      [SHINDO.SHINDO_6_WEAK]: 1,
      [SHINDO.SHINDO_6_STRONG]: 3,
      [SHINDO.SHINDO_7]: 0,
    },
    total: 178,
  },
];
